### ISSUE TITLE
Capslock Key Broken

### ISSUE THREAD

**Issue by ihoegen** [babin101/DevKeyboard#19] opened 2015-07-28 17:09 UTC
After using through autohotkey, capslock does not work on my keyboard.

**Comment by LudwikJaniuk** [comment] 2015-07-28 17:15
Could you add some more detail? Do you mean the caps lock key stops working completely if you turn on DevKeyboard, or something else, i.e. it stops working if you add it as one of the keys in the settings, or that you can't use it through the settings and that's what you mean by "not working"?

Also, if anything but the last option: does it start working again after you turn DevKeyboard off?

**Comment by ihoegen** [comment] 2015-07-28 18:31
The capslock key completely stops working when DevKeyboard is turned on. When DevKeyboard is turned off, it works

**Comment by LudwikJaniuk** [comment] 2015-07-28 19:05
**Okay, I've reproduced it as well, this is a valid issue.** When you turn DevKeyboard off with Super-J (Windows key + J), it starts working again, right? 

Note however that the caps lock key itself is not what's "not working". I can still press it on or off and the little indicator light that I have on my laptop will go on/off. In other words, the problem most likely lies in that DevKeyboard intercepts your keystrokes, but then sends lowercase letters without considering whether you have Caps on or off. 

An interesting thing is that if you hold shift, you do get uppercase letters. On second thought, this is kind of expected since DevKeyboard does not seem to intercept your keystrokes if you're holding shift anyways. For instance, if you hold Shift and hold H for your set time, it won't turn it into a >.

Anyways, hope that @babin101 will see this soon. In the meantime, seems like you'll have to use Super + J for writing CAPS.

**Comment by LudwikJaniuk** [comment] 2015-07-28 19:06
Also, do you remember if it did work in any previous release, and if so, which one?

**Comment by ihoegen** [comment] 2015-07-28 20:49
I do not remember it working in any previous releases.

**Comment by LudwikJaniuk** [comment] 2015-07-28 21:05
Ok, I checked with a lot of the earlier versions, and you're right, it seems like this bug was here from the beginning. It's surprising no one saw it. However, ( @babin101 listen here), it seems like the problem was a bit different in commit cbfb34f and presumably earlier: in that commit, the capslock _does_ work with keys that are not mapped, i.e. Q, W, E. Interesting.

**Comment by ihoegen** [comment] 2015-07-28 21:15
I've tried redefining the capslock key to capslock at the very end, with no success.

**Comment by LudwikJaniuk** [comment] 2015-07-28 21:19
You what? Please explain, I don't understand what you mean by "redefining the capslock key".

**Comment by ihoegen** [comment] 2015-07-28 21:54
Appending

```
Capslock::Capslock
```

to the file

**Comment by LudwikJaniuk** [comment] 2015-07-28 21:59
The AHK file? Oh, ok. Yeah, I wouldn't have thought that would work. As said, the Capslock keypress does get registered (and your caps state does change), it's just that DevKeyboard catches all letter characters and either sends out their replacement or their "real" value, just that it does not take into account whether caps are on or off, so e.g. when the "G" key is pressed, it will always either send lowercase "g" or, after the set time, "<", because that's how it was programmed.

(Or at least that's my theory, I haven't actually read that part of the source).

**Comment by benwoodman** [comment] 2015-07-28 22:17
I will definitely work on this right away, thanks for bringing it to my attention.

**Comment by benwoodman** [comment] 2015-07-30 11:34
Okay, so I don't really know what do here. I really want to keep this program as lightweight as possible, so checking if capslock is on everytime someone hits a key is not a great way to do this. I have also tried to treat the capslock key as a shift key but this caused major bugs to my computer (I had to restart). Do you have any ideas on how to achieve this?

**Comment by LudwikJaniuk** [comment] 2015-07-30 11:45
Is checking caps state really that heavy of an operation? I thought it would add no measurable overhead whatsoever. But, if you do want to make it lighter than that, would it be possible to keep an internal "caps state" variable and only update it when the user presses the caps lock key? And then when sending letters, reference this variable instead of checking for the actual caps lock state. Would something like that work?

**Comment by benwoodman** [comment] 2015-07-30 11:53
Okay, I think I have a solution, I'll post it in a sec

**Comment by benwoodman** [comment] 2015-07-30 12:20
Okay, go ahead and try out the new DevKeyboard.ahk file, I think I've fixed it

**Comment by LudwikJaniuk** [comment] 2015-07-30 12:28
I'll try it. Internet is spotty, might be a few minutes. 

A question in the meantime, you probably thought of this but just in case: when updating the caps variable, did you set it to the actual state of the caps key, or just the reverse of what it was before? Because if the second option is true, then you're fucked if AHK just happens to miss one caps press (and I wouldn't count that as completely impossible). If you went with the first solution howerver then all is good, because even if AHK somehow missed a press, one could just press Caps again and it would be fixed. 

Or maybe you went with an entirely different approach?

**Comment by LudwikJaniuk** [comment] 2015-07-30 12:32
Okay, I'm testing it. It sure works...

However, I'm not sure what you did but this is scary: caps lock is not changing the indicator light on my laptop anymore. Assuming you're somehow intercepting Caps completely? Good job, but... I feel kind of uneasy with this. Are you sure it's necessary? Can't your script react to Caps being pressed without also disabling it?

**Comment by benwoodman** [comment] 2015-07-30 12:33
No, I didn't set the state of the caps key, when I tried that it totally screwed up my computer. I went with a new approach. I just set a variable - capsState - to have a variable of 1 or 0, and capitalize all the letters. The only problem is, now the capslock light on the keyboard doesn't light up. I can try a different approach though.

**Comment by LudwikJaniuk** [comment] 2015-07-30 12:36
Yeah, as you're saying, the light on the keyboard doesn't light up. Other than that everything works pretty much perfect, but it is a bit disconcerning not seeing the light change.

**Comment by benwoodman** [comment] 2015-07-30 12:39
Okay, I'll work on that

**Comment by benwoodman** [comment] 2015-07-30 12:58
Allright, I think I've fixed it. Go ahead and test it out

**Comment by LudwikJaniuk** [comment] 2015-07-30 12:58
Will do, sec

**Comment by LudwikJaniuk** [comment] 2015-07-30 13:03
Works like a charm, indicator light and all. Perfect!

**Comment by benwoodman** [comment] 2015-07-30 13:07
Awesome, I'm gonna close this issue now

**Closed as completed by benwoodman** 2015-07-30 13:07 UTC
Labels: bug
